# Site
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Matthijs P.
title: Senior Software Engineer
email: m.piek@hotmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  mpiek
# stackoverflow_username: ""
instagram_username: algathonix
linkedin_username: matthijs-piek-908738225


# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs


sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
